apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-hello-world-ingress
  namespace: test
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - test.thingly.net
    secretName: test.thingly.net-tls
  rules:
  - host: test.thingly.net
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: flask-hello-world
            port:
              number: 80
